name: check
on:
  workflow_call:
jobs:
  run:
    # renovate: datasource=git-refs depName=nwarila-platform/.github packageName=https://github.com/nwarila-platform/.github.git currentValue=main
    uses: nwarila-platform/.github/.github/workflows/run-container.yaml@02e86bfc0da31ad95718996e05cf376a3d6c30c4
    permissions:
      contents: read
      pull-requests: write
    with:
      name: template-drift
      version: 2.0.0
