name: Workflow containers
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  template-drift:
    # renovate: datasource=git-refs depName=nwarila-platform/workflow-template-drift packageName=https://github.com/nwarila-platform/workflow-template-drift.git currentValue=main
    uses: nwarila-platform/workflow-template-drift/.github/workflows/check.yaml@d20e0fd946ed87001b582ac88d868a9b45cde839 # v2.1.0
