name: Workflow containers
on:
  pull_request:
  push:
    branches: [main]
permissions: {}
jobs:
  template-drift:
    permissions: {contents: read, security-events: write}
    # renovate: datasource=git-refs depName=nwarila-platform/workflow-template-drift packageName=https://github.com/nwarila-platform/workflow-template-drift.git currentValue=main
    uses: nwarila-platform/workflow-template-drift/.github/workflows/check.yaml@3ac6d2f3ce65e2f98963826e71ad9e79c5e43c09
    with:
      version: 3.0.0
      digest: sha256:62572efee0743177480a0fb455dae1bc714158395b20aeb0c4b57dd830829e08
